# Generated by Django 5.1.4 on 2025-01-22 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ML', 'Masala Latte'), ('CL', 'Chai Latte'), ('CH', 'Chai'), ('IC', 'Iced Chai'), ('EL', 'Elachi Chai')], max_length=2)),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
