# Generated by Django 5.1.4 on 2025-01-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivariety',
            name='images',
            field=models.ImageField(upload_to='chai_images/'),
        ),
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('variety', models.ManyToManyField(related_name='stores', to='chai.chaivariety')),
            ],
        ),
    ]
